galeria:
    path:     /
    defaults: { _controller: "DistritoCaseriosBundle:Galeria:index" }

galeria_show:
    path:     /{id}/show
    defaults: { _controller: "DistritoCaseriosBundle:Galeria:show" }

galeria_new:
    path:     /new
    defaults: { _controller: "DistritoCaseriosBundle:Galeria:new" }

galeria_create:
    path:     /create
    defaults: { _controller: "DistritoCaseriosBundle:Galeria:create" }
    methods:  POST

galeria_edit:
    path:     /{id}/edit
    defaults: { _controller: "DistritoCaseriosBundle:Galeria:edit" }

galeria_update:
    path:     /{id}/update
    defaults: { _controller: "DistritoCaseriosBundle:Galeria:update" }
    methods:  [POST, PUT]

galeria_delete:
    path:     /{id}/delete
    defaults: { _controller: "DistritoCaseriosBundle:Galeria:delete" }
    methods:  [POST, DELETE]
